#!/bin/bash
  
# check if java exists
[[ -z $(which java) ]] && echo "Error: cannot find java." 1>&2 && exit 1

CWD=$(pwd)

BIN=$(dirname ${BASH_SOURCE[0]})

LIB=$(cd ${BIN}/../../lib && pwd)

cd $LIB

for f in $(ls -d mexplorer-*.jar)
do
    JAR=$f
done

[[ -z ${JAR} ]] && echo "Error: cannot find mexplorer-*.jar in ${LIB}" && exit 2

cd $CWD

java -jar ${LIB}/${JAR}